version: '3.9'
services:
  vercel-notion-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces/vercel-notion-api
      - vercel-notion-api-volume:/workspaces/vercel-notion-api/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_ID=$DATABASE_ID
      - SECRET_TOKEN=$SECRET_TOKEN
volumes:
  vercel-notion-api-volume: